// Nameing: PAGE_ACTION_STATUS

export const HOME_EDITFORM_CHANGE = 'HOME_EDITFORM_CHANGE'
export const HOME_SETVARIABLE_LOAD = 'HOME_SETVARIABLE_LOAD'
export const HOME_SETVARIABLE_SUCCEED = 'HOME_SETVARIABLE_SUCCEED'
export const HOME_SETVARIABLE_FAIL = 'HOME_SETVARIABLE_FAIL'
